#!/bin/sh
if [ -n "$HOME" ];then
    cp -n /etc/xdg/kglobalshortcutsrc $HOME/.config/kglobalshortcutsrc
fi
QT_SCALE_FACTOR=1 kwin_x11 -platform dde-kwin-xcb:appFilePath=$(cd `dirname $0`; pwd)/kwin_no_scale $@
